---
title: "Final Project"
author: "Group 4"
date: "5/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r}
schools <- read_xlsx("US_schools_data.xlsx")
```

```{r}
clean_schools <-schools %>%
  select(PRIMARY_KEY,
         TOTAL_EXPENDITURE, 
         INSTRUCTION_EXPENDITURE, 
         SUPPORT_SERVICES_EXPENDITURE, 
         OTHER_EXPENDITURE, 
         CAPITAL_OUTLAY_EXPENDITURE, 
         ends_with("READING"), 
         ends_with("MATHEMATICS"))
```
```{r}
clean_schools
```

```{r}

clean_schools$PRIMARY_KEY <- str_replace(clean_schools$PRIMARY_KEY,"_", " ")

clean_schools <- clean_schools %>%
  separate(PRIMARY_KEY, 
           into = c("year", "state"), 
           sep = " ")

clean_schools$state <- str_replace_all(clean_schools$state, "_", " ")


```

```{r}
clean_schools <- clean_schools %>%
  pivot_longer("G04_A_A_READING":"G08_TR_A_MATHEMATICS",
               names_to = c("grade","race", "sex", "test"),
               names_sep = "_",
               values_to = "score")
```


```{r}
clean_schools <- clean_schools %>%
  mutate(sex = as.factor(sex),
         race = fct_recode(as.factor(clean_schools$race), 
                           all = "A",
                           asian = "AS",
                           hispanic = "HI",
                           black = "BL",
                           white = "WH",
                           pacific_islander = "HP",
                           two_or_more = "TR"),
         test = as.factor(test),
         grade =as.factor(grade)
         )
  
```


```{r}
MIDWEST <- c("INDIANA","ILLINOIS","MICHIGAN","OHIO","WISCONSIN",
             "IOWA","KANSAS","MINNESOTA","MISSOURI","NEBRASKA",
             "NORTH DAKOTA","SOUTH DAKOTA")

NORTHEAST <- c("CONNECTICUT","MAINE","MASSACHUSETTS","NEW HAMPSHIRE",
             "RHODE ISLAND","VERMONT","NEW JERSEY","NEW YORK",
             "PENNSYLVANIA")

SOUTH <- c("DELAWARE","DISTRICT","FLORIDA","GEORGIA",
            "MARYLAND","NORTH CAROLINA","SOUTH CAROLINA","VIRGINIA",
            "WEST VIRGINIA","ALABAMA","KENTUCKY","MISSISSIPPI",
            "TENNESSEE","ARKANSAS","LOUISIANA","OKLAHOMA","TEXAS")

WEST <- c("ARIZONA","COLORADO","IDAHO","NEW MEXICO","MONTANA",
            "UTAH","NEVADA","WYOMING","ALASKA","CALIFORNIA",
            "HAWAII","OREGON","WASHINGTON")

clean_schools <- clean_schools %>%
  mutate(region = if_else(state %in% MIDWEST, "Midwest", 
                          if_else(state %in% NORTHEAST, "Northeast", 
                                  if_else(state %in% SOUTH, "South", 
                                          if_else(state %in% WEST, "West", "Other")))))

```


```{r}
clean_schools %>%
  ggplot(aes(x = INSTRUCTION_EXPENDITURE, y = score, color = race)) +
  geom_point() +
  labs(x = "Instructional Expenditures ($)", 
       y = "Testing scores")  +
  facet_wrap(~race)

clean_schools %>%
  ggplot(aes(x = INSTRUCTION_EXPENDITURE, y = score, color = sex)) +
  geom_point() +
  labs(x = "Instructional Expenditures ($)", 
       y = "Testing scores")  +
  facet_wrap(~sex)
```

```{r visuals}
clean_schools %>%
  ggplot()+
  geom_density(mapping = aes(x = score, fill = test), alpha = 0.5)+
  facet_wrap(~race) +
  labs(title = "Math and Test Scores Density", x = "Test Scores", fill = "Test")

clean_schools %>%
  ggplot()+
  geom_density(mapping = aes(x = score, fill = test), alpha = 0.5)+
  facet_wrap(~sex) +
  labs(title = "Math and Test Scores Density", x = "Test Scores", fill = "Test")
```
```{r}
clean_schools %>%
  #filter(!is.na(INSTRUCTION_EXPENDITURE)) %>%
  group_by(year, region, race, sex) %>%
  mutate( INSTRUCTION_EXPENDITURE = INSTRUCTION_EXPENDITURE / 1000000,
    avg = mean(INSTRUCTION_EXPENDITURE, na.rm = TRUE),
         year = as.factor(year)) %>%
  ggplot(mapping = aes(x = year, y = avg, color = region))+
  geom_point() +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +#+ facet_wrap(~race) + facet_wrap(~sex)
  labs(title = "Average Instruction Expenditure over time for the different regions", y = "Average Instruction Expenditure (in millions $)", x = "Year")
```

```{r visuals}
clean_schools %>%
  group_by(year, region) %>%
  mutate(
    INSTRUCTION_EXPENDITURE = INSTRUCTION_EXPENDITURE / 1000000,
    avg = mean(INSTRUCTION_EXPENDITURE, na.rm = TRUE),
<<<<<<< HEAD
         year = as.factor(year)
    ) %>%
  ggplot(mapping = aes(x = year, y = avg, color = region))+
  geom_point() +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +#+ facet_wrap(~race) + facet_wrap(~sex)
  labs(title = "Average Instruction Expenditure over time for the different regions", y = "Average Instruction Expenditure", x = "Year")
=======
         year = as.factor(year)) %>%
  ggplot(mapping = aes(x = year, 
                       y = avg,
                       group = region,
                       color = fct_reorder2(region, year, INSTRUCTION_EXPENDITURE)))+
  geom_line() +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +
  #scale_colour_brewer(palette = "Paired") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        text=element_text(size=12, 
                          family="serif"),
                          axis.text.y = element_text(size = 16))+
  # code for removing gridlines from https://felixfan.github.io/ggplot2-remove-grid-background-margin/
  # code for font from https://stackoverflow.com/questions/34522732/changing-fonts-in-ggplot2
  # annotation from https://ggplot2.tidyverse.org/reference/annotate.html
  labs(title = "Average Instruction Expenditure Over Time by Region",
       x = "Year",
       y = "Average Instruction Expenditure (Millions $)",
       color = "Region")+
  annotate("text", 
           x = "2012", 
           y = 5.75, 
           label = "Large increase \n for Northeast",
           size = 2)

>>>>>>> d36ae62ef5890391d3d5b643a971c24f2e8c31c1
```


```{r}
clean_schools %>%
  filter(test == "MATHEMATICS",
         !is.na(score)) %>%
  lm(score ~ INSTRUCTION_EXPENDITURE, data = .) ->
  math_model

clean_schools %>%
  filter(test == "READING",
         !is.na(score)) %>%
  lm(score ~ INSTRUCTION_EXPENDITURE, data = .) ->
  reading_model
```

```{r}
summary(math_model)
# math model has higher r^2
summary(reading_model)
```


```{r}
clean_schools %>%
  lm(score ~ test, data = .) ->
  test_model
summary(test_model)
```

```{r}
clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  lm(score ~ test + year, data = .) %>%
  summary()
```
```{r}
clean_schools %>%
  mutate(year = as.numeric(year),
         state = as.factor(state)) %>%
  lm(score ~ test + year + SUPPORT_SERVICES_EXPENDITURE, data = .) %>%
  summary()
```

```{r}
clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  lm(score ~ test + year + region + SUPPORT_SERVICES_EXPENDITURE, data = .) %>%
  summary()
```

```{r}
clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  lm(score ~ test + year + region + SUPPORT_SERVICES_EXPENDITURE + race, data = .) %>%
  summary()
```

```{r}
clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  lm(score ~ test + year + region + race, data = .) %>%
  summary()
```

```{r}
clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  lm(score ~ test + year + region + SUPPORT_SERVICES_EXPENDITURE + race + grade, data = .) %>%
  summary()
```

```{r}
clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  lm(score ~ test + year + region +  race + grade + INSTRUCTION_EXPENDITURE, data = .) %>%
  summary()
```
** Selected model **

```{r}
clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  lm(score ~ test + year + region + race + grade + INSTRUCTION_EXPENDITURE, data = .) %>%
  summary()
```

```{r visualization of model, echo = FALSE}
clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  #filter(race != "all") %>%
  ggplot(mapping = aes(x = year, 
                           y = score,
                           color = race))+
  geom_point()+
  geom_jitter()+
  #stat_smooth(method = "lm")+
  facet_grid(rows = vars(test), cols = vars(grade))+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
```

```{r}
schools_lm <- clean_schools %>%
  mutate(year = as.numeric(year)) %>%
  lm(score ~ test + year + region + race + grade + INSTRUCTION_EXPENDITURE, data = .)
schools_predict <- predict(schools_lm)
schools_sigma <- sigma(schools_lm)
```

```{r Function to add Errors}
noise <- function(x, mean = 0, sd){
  n <- length(x)
  new_data <- x + rnorm(n, mean, sd)
  return(new_data)
}
```

```{r Making Tibble of Predictions}
new_data <- tibble(
  predict_score = noise(schools_predict,
                         sd = schools_sigma)
)
```

```{r Removing NAs From Observed}
new_data <- clean_schools %>% 
  filter(!is.na(score), 
         !is.na(test), 
         !is.na(year),
         !is.na(region),
         !is.na(race),
         !is.na(grade),
         !is.na(INSTRUCTION_EXPENDITURE)) %>% 
  select(score, test, year, region, race, grade,
         INSTRUCTION_EXPENDITURE) %>% 
  bind_cols(new_data)
```

```{r Iterating Simulations}
nsims <- 1000

sims <- map_dfc(1:nsims,
                ~tibble(sim = noise(schools_predict, sd = schools_sigma)))
```

```{r Replacing column names ... with _}
colnames(sims) <- colnames(sims) %>% 
  str_replace(pattern = "\\.\\.\\.",
                  replace = "_")
```

```{r Add Observed into Simulated}
sims <- clean_schools %>% 
filter(!is.na(score), 
         !is.na(test), 
         !is.na(year),
         !is.na(region),
         !is.na(race),
         !is.na(grade),
         !is.na(INSTRUCTION_EXPENDITURE)) %>%  
  select(score) %>% 
  bind_cols(sims)
```

```{r}
sim_r_sq <- sims %>% 
  map( ~lm(score ~ .x, data = sims)) %>% 
  map(broom::glance) %>% 
  map_dbl(~.$r.squared)
```

```{r}
sim_r_sq <- sim_r_sq[names(sim_r_sq) != "score"]
head(sim_r_sq)
```

```{r}
tibble(sims = sim_r_sq) %>% 
  ggplot(aes(x = sims)) + 
  geom_histogram()
```

